---
- name: Converge
  hosts: all

  vars:
  #   controller_fqdn:
  #   user_email:
  #   user_password:

  tasks:
    - include_role:
        name: ansible-role-nginx-controller-generate-token

  post_tasks:
    - debug:
        msg: "{{ controller_auth_token }}"
