---
- name: Converge
  hosts: all

  vars:
  #   controller_fqdn:
  #   user_email:
  #   user_password:

  tasks:
    - include_role:
        name: ansible_role_nginx_controller_generate_token

  post_tasks:
    - debug:
        msg: "{{ controller_auth_token }}"
