---
- name: Verify
  hosts: mock_server
  connection: local
  tasks:
    - name: Check that the login request was sent to the mock controller exactly twice per docker instance (includes the idempotence test)
      uri:
        url: "https://{{ inventory_hostname }}:1080/mockserver/verify"
        method: PUT
        body:
          httpRequest:
            path: "/api/v1/platform/login"
          times:
            atLeast: 8
            atMost: 8
        status_code: 202
        body_format: json
        headers:
          Content-Type: application/json
        validate_certs: false
